name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # deploy on push to main branch
#on:
#  workflow_dispatch: #uncomment for manual only 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Wrangler (Cloudflare CLI)
        run: npm install -g wrangler
        
      - name: Wrangler version
        run: wrangler --version
        
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: "site"
          command: pages deploy . --project-name=cv-valentin
